# Generated by Django 4.2.4 on 2023-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0002_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
