# Generated by Django 4.2.4 on 2023-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0003_alter_dish_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default='item', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
