# Generated by Django 4.2.4 on 2023-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudOperations', '0004_remove_order_items_remove_order_items_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalprice',
            name='total_sales',
            field=models.FloatField(default=0),
        ),
    ]
